#!/usr/bin/env python3

# Copyright (c) 2020, Ericson Joseph
# 
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
# 
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright notice,
#       this list of conditions and the following disclaimer in the documentation
#       and/or other materials provided with the distribution.
#     * Neither the name of pyMakeTool nor the names of its contributors
#       may be used to endorse or promote products derived from this software
#       without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

from logging import setLoggerClass
from pathlib import Path
import json
import tempfile
import subprocess
from pymakelib import Pymaketool
from pymakelib import prelib as plib
import sys

p = Pymaketool()

print(p.getModulesPaths())

modules = p.readModules(p.getModulesPaths())

lincs = ''
allincs = []
# allincs.extend(p.compilerSettings['INCLUDES'])

allsrcs = []

for m in modules:
    incs = [str(i) for i in m.incs]
    allincs.extend(incs)
    print(m.filename)
    if str(m.filename) in sys.argv:
        print("add src")
        srcs = [str(s) for s in m.srcs]
        allsrcs.extend(srcs)
    
# allsrcs = list(dict.fromkeys(allsrcs))

# includes = ','.join(allincs)
# srcs = ','.join(allsrcs)

# print(f"./cinclude2dot --include={includes} --src={srcs}")
## Use gcc -H -D__TEST_DEFINE__=1 -I/PROJECTS/PYTHON/test_module_lib/module_lib/inc -Ilib/inc app/application/main.c

gccCmd = ['echo', '|']
gccCmd.append(p.compilerSettings['CC'])
gccCmd.append('-H')
gccCmd.append(plib.macrosDictToString(p.compilerOpts['MACROS']))
for inc in allincs:
    gccCmd.append(f"-I{inc}")
gccCmd.append('-o')
tmpout = tempfile.NamedTemporaryFile()
gccCmd.append(tmpout.name)
gccCmd.append('-c')
gccCmd.append('&>')
tmpfile = tempfile.NamedTemporaryFile()
gccCmd.append(tmpfile.name)
gccCmd.append(';')
gccCmd.append('cat')
gccCmd.append(tmpfile.name)
gccCmd.append('|')
gccCmd.append('grep')
gccCmd.append('-e')
gccCmd.append("'^. '")

class Node:
    def __init__(self, pathsrc:str, modulespaths):
        self.pathsrc = Path(pathsrc)
        self.name = self.pathsrc.name
        self.group = None
        self.modulespaths = modulespaths
        for modpath in modulespaths:
            if Path(modpath.parent) in self.pathsrc.parents:
                self.group = modpath.parent.name
                break
        if not self.group:
            self.group = self.pathsrc.parent
            if str(self.group).endswith('src') or  str(self.group).endswith('inc'):
                self.group = self.group.parent
        self.incs = None
        if pathsrc.endswith('.c'):
            self.incs = self.getIncludes(pathsrc)

    def getIncludes(self, src):
        incs = []
        gccCmd.insert(12, src)
        stcmd = ' '.join(gccCmd)
        try:
            out = subprocess.check_output(['bash', '-c', stcmd])
            for line in out.splitlines():
                line = line.decode('utf-8')
                line = line[2:]
                incs.append(Node(f"{line}", self.modulespaths))
        except Exception as e:
            print(e)
        gccCmd.pop(12)
        return incs

    def getKey(self):
        return self.name.replace('.', '_')

    def __repr__(self) -> str:
        return f"pathsrc: {self.pathsrc}, name: {self.name}, group: {self.group}, incs: {self.incs}"

print("digraph module {")

nodes = {}
groups = {}

for src in allsrcs:
    n = Node(src, p.getModulesPaths())
    if not n.name in nodes:
        nodes[n.name] = n
    if not n.group in groups:
        groups[n.group] = [n]
    else:
        groups[n.group].append(n)
    for i in n.incs:
        if not i.name in nodes:
            nodes[i.name] = i
        if not i.group in groups:
            groups[i.group] = [i]
        else:
            groups[i.group].append(i)
        if not i.group == n.group: 
            print(f"    {n.getKey()} -> {i.getKey()};")


print('\n')
idx = 0
for g in groups:
    print(f"    subgraph cluster_{idx} "+"{")
    idx += 1
    nds = groups[g]
    for n in nds:
        if n.incs:
            aloneingroup = True
            for i in n.incs:
                if i.group == g:
                    aloneingroup = False
                    print(f"        {n.getKey()} -> {i.getKey()};")
            if aloneingroup:
                print(f"        {n.getKey()};")
        else:
            print(f"        {n.getKey()};")
    print(f"        label = \"{g}\";")
    print(f"        color = blue;")
    print("    }")

print('\n')
for n in nodes:
    n = nodes[n]
    print(f"    {n.getKey()} [shape=box label=\"{n.name}\"];")

print("}")

# for g in groups:
#     print('\n')
#     print(groups[g])